// <auto-generated />
using System;
using Cambialo.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Cambialo.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20201114054221_InitialDb")]
    partial class InitialDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Cambialo.Api.Data.Entities.Article", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("OfferChangeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RequestedChangeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OfferChangeId");

                    b.HasIndex("RequestedChangeId");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("Cambialo.Api.Data.Entities.Change", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ChangeStatus")
                        .HasColumnType("int");

                    b.Property<int>("ChangeType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FinishedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Changes");
                });

            modelBuilder.Entity("Cambialo.Api.Data.Entities.Article", b =>
                {
                    b.HasOne("Cambialo.Api.Data.Entities.Change", "OfferChange")
                        .WithMany("OffertedArticles")
                        .HasForeignKey("OfferChangeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Cambialo.Api.Data.Entities.Change", "RequestedChange")
                        .WithMany("RequestedArticles")
                        .HasForeignKey("RequestedChangeId")
                        .OnDelete(DeleteBehavior.NoAction);
                });
#pragma warning restore 612, 618
        }
    }
}
